### PR TITLE
Fix sorting by tags and console errors

### LINKED ISSUE #207: Tag sorting produces incorrect results
when I try to sort by tag the sorting does not work properly. I have tags 1, 2, 3. You would expect to have tasks with tag 1 then tag two then tag three or the other way around depending on asc or dsc.  However, they are not in any logical order. 

I had claude code try to help me with this and it came up with this bug. I don't know enough to know if the following is accurate so take it for what its worth. 

In frontend/src/App.jsx, the sortCardsByTags() function has a bug in the descending comparison:

  function sortCardsByTags() {
    const newCards = structuredClone(cards());
    return newCards.sort((a, b) => {
      return sortDirection() === "asc"
        ? a.tags[0]?.name.localeCompare(b.tags?.[0])      // ← Missing .name
        : b.tags[0]?.name.localeCompare(a.tags?.[0]);     // ← Missing .name
    });
  }

  Both branches are missing the .name accessor on the second parameter. The localeCompare() receives a tag object instead of a tag name string.

  Suggested Fix:

  function sortCardsByTags() {
    const newCards = structuredClone(cards());
    return newCards.sort((a, b) => {
      return sortDirection() === "asc"
        ? a.tags[0]?.name.localeCompare(b.tags?.[0]?.name)
        : b.tags[0]?.name.localeCompare(a.tags?.[0]?.name);
    });
  }

  Add ?.name to both second parameters to ensure both tag names are strings before comparison.

  Additional Considerations:

  The function should also handle cards with no tags more gracefully. Currently, cards without tags may cause issues. Consider:

  function sortCardsByTags() {
    const newCards = structuredClone(cards());
    return newCards.sort((a, b) => {
      const aTag = a.tags?.[0]?.name || '';
      const bTag = b.tags?.[0]?.name || '';
      return sortDirection() === "asc"
        ? aTag.localeCompare(bTag)
        : bTag.localeCompare(aTag);
    });
  }

### PR DESCRIPTION
**Pull request by BaldissaraMatheus**
Fix #207

### CODE REVIEW

File: frontend/src/components/expanded-card.jsx [hunk 1]
```diff
@@ -307,7 +307,6 @@ function ExpandedCard(props) {
     }
     e?.preventDefault();
     if (newCardName() || isCreatingNewTag()) {
-      setNameInputValue(null);
       setIsCreatingNewTag(false);
       return;
```
Comment (Mesaa-star) [inline frontend/src/components/expanded-card.jsx]: go
